//! Did the fix hold?
//!
//! An agent that opens a pull request (`issue_analyses.fix_url`) makes a claim about production.
//! Thermite is the only thing positioned to check it, and it needs no new bookkeeping to do so:
//! releases are already ordered by first sighting, and `issue_tags` already records which releases
//! an issue was seen in. The verdict is *derived* on read — nothing is written at ingest, and
//! nothing has to be maintained.
//!
//! Three states, and the boundaries between them are the whole design:
//!
//! - `pending` — no release has shipped since the fix was proposed. There is nothing to judge yet,
//!   and saying so is more useful than an optimistic `held`.
//! - `held` — releases have shipped since, and the issue was seen in none of them.
//! - `regressed` — the issue was seen in a release that first appeared after the fix was proposed.
//!
//! Two limits worth stating plainly, because a scoreboard that overstates its own certainty is
//! worse than none:
//!
//! - **A release shipping does not prove the fix was in it.** If a deploy goes out without the
//!   merge and the bug recurs, this reads as `regressed`. That is the conservative direction: it
//!   can under-credit an agent, but it never reports a fix as holding while the bug is live.
//! - **`held` decays with retention.** The release tags it reads age out with
//!   `THERMITE_RETENTION_DAYS`, so a recurrence older than the window is invisible. Fixes are
//!   graded in the days after they ship, which is well inside it.

use axum::Json;
use axum::extract::{Path, Query, State};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sqlx::PgPool;

use crate::error::{AppError, AppResult};
use crate::state::ThermiteState;

/// What production says about one proposed fix.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Verdict {
    Pending,
    Held,
    Regressed,
}

impl Verdict {
    pub fn as_str(self) -> &'static str {
        match self {
            Verdict::Pending => "pending",
            Verdict::Held => "held",
            Verdict::Regressed => "regressed",
        }
    }
}

/// One graded fix.
#[derive(Debug, Serialize)]
pub struct Fix {
    pub analysis_id: i64,
    pub issue_id: i64,
    pub project_slug: String,
    pub issue_title: String,
    /// Which agent proposed it — the same free-form identifier `post_analysis` carries.
    pub source: String,
    pub fix_url: String,
    pub proposed_at: DateTime<Utc>,
    pub verdict: Verdict,
    /// Releases first seen after the fix was proposed. Zero is what makes a verdict `pending`.
    pub releases_since: i64,
    /// For a `regressed` verdict, the first release since the fix that the issue was seen in.
    pub regressed_in: Option<String>,
}

/// An agent's record, which is the point: a fix rate is an eval signal generated by production
/// rather than by a benchmark.
#[derive(Debug, Serialize)]
pub struct SourceRecord {
    pub source: String,
    pub held: i64,
    pub regressed: i64,
    pub pending: i64,
    /// Held over settled (held + regressed). `None` while nothing has settled — a rate over zero
    /// samples reads as a fact and measures nothing.
    pub hold_rate: Option<f64>,
}

#[derive(Debug, Serialize)]
pub struct FixRecord {
    pub fixes: Vec<Fix>,
    pub by_source: Vec<SourceRecord>,
}

#[derive(Debug, Deserialize)]
pub struct FixQuery {
    limit: Option<i64>,
}

const MAX_LIMIT: i64 = 200;

#[derive(sqlx::FromRow)]
struct Row {
    analysis_id: i64,
    issue_id: i64,
    project_slug: String,
    issue_title: String,
    source: String,
    fix_url: String,
    proposed_at: DateTime<Utc>,
    releases_since: i64,
    regressed_in: Option<String>,
}

/// `GET /api/v1/fixes` — every proposed fix, graded.
pub async fn list(
    State(state): State<ThermiteState>,
    Query(query): Query<FixQuery>,
) -> AppResult<Json<FixRecord>> {
    Ok(Json(record(&state.db, None, query.limit).await?))
}

/// `GET /api/v1/projects/{slug}/fixes` — the same, for one project.
pub async fn project(
    State(state): State<ThermiteState>,
    Path(slug): Path<String>,
    Query(query): Query<FixQuery>,
) -> AppResult<Json<FixRecord>> {
    Ok(Json(record(&state.db, Some(&slug), query.limit).await?))
}

/// Shared with the MCP `fix_record` tool.
pub async fn record(db: &PgPool, slug: Option<&str>, limit: Option<i64>) -> AppResult<FixRecord> {
    if let Some(slug) = slug {
        let exists: Option<(i64,)> = sqlx::query_as("select id from projects where slug = $1")
            .bind(slug)
            .fetch_optional(db)
            .await?;
        if exists.is_none() {
            return Err(AppError::NotFound);
        }
    }

    let limit = limit.unwrap_or(MAX_LIMIT).clamp(1, MAX_LIMIT);

    // Both correlated subqueries are per-analysis and hit indexed columns; the set is bounded by
    // how many fixes were ever proposed, which is orders of magnitude below the event tables.
    let rows: Vec<Row> = sqlx::query_as(
        "select a.id                as analysis_id,
                a.issue_id          as issue_id,
                p.slug              as project_slug,
                i.title             as issue_title,
                a.source            as source,
                a.fix_url           as fix_url,
                a.created_at        as proposed_at,
                (select count(*) from releases r
                  where r.project_id = i.project_id
                    and r.first_seen > a.created_at)::bigint as releases_since,
                -- The earliest release since the fix that this issue was actually seen in. Read
                -- from the tag rollup rather than `events`: it is the same source the environment
                -- and release filters use, and it survives the events themselves.
                (select r.version
                   from issue_tags t
                   join releases r
                     on r.project_id = i.project_id and r.version = t.value
                  where t.issue_id = a.issue_id
                    and t.key = 'release'
                    and r.first_seen > a.created_at
                  order by r.first_seen
                  limit 1) as regressed_in
           from issue_analyses a
           join issues   i on i.id = a.issue_id
           join projects p on p.id = i.project_id
          where a.fix_url is not null
            and ($1::text is null or p.slug = $1)
          order by a.created_at desc
          limit $2",
    )
    .bind(slug)
    .bind(limit)
    .fetch_all(db)
    .await?;

    let fixes: Vec<Fix> = rows
        .into_iter()
        .map(|row| Fix {
            verdict: verdict(row.regressed_in.is_some(), row.releases_since),
            analysis_id: row.analysis_id,
            issue_id: row.issue_id,
            project_slug: row.project_slug,
            issue_title: row.issue_title,
            source: row.source,
            fix_url: row.fix_url,
            proposed_at: row.proposed_at,
            releases_since: row.releases_since,
            regressed_in: row.regressed_in,
        })
        .collect();

    Ok(FixRecord {
        by_source: tally(&fixes),
        fixes,
    })
}

/// The rule, in one place: a recurrence settles it, otherwise a release having shipped is what
/// makes silence mean anything.
fn verdict(regressed: bool, releases_since: i64) -> Verdict {
    if regressed {
        Verdict::Regressed
    } else if releases_since > 0 {
        Verdict::Held
    } else {
        Verdict::Pending
    }
}

fn tally(fixes: &[Fix]) -> Vec<SourceRecord> {
    let mut sources: Vec<SourceRecord> = Vec::new();

    for fix in fixes {
        let record = match sources.iter_mut().find(|r| r.source == fix.source) {
            Some(record) => record,
            None => {
                sources.push(SourceRecord {
                    source: fix.source.clone(),
                    held: 0,
                    regressed: 0,
                    pending: 0,
                    hold_rate: None,
                });
                sources.last_mut().expect("just pushed")
            }
        };

        match fix.verdict {
            Verdict::Held => record.held += 1,
            Verdict::Regressed => record.regressed += 1,
            Verdict::Pending => record.pending += 1,
        }
    }

    for record in &mut sources {
        let settled = record.held + record.regressed;
        record.hold_rate = (settled > 0).then(|| record.held as f64 / settled as f64);
    }

    sources.sort_by(|a, b| a.source.cmp(&b.source));
    sources
}

/// Grades the analyses on one issue in a single round trip, so the issue page can badge each
/// proposed fix with what became of it. Analyses without a `fix_url` are left alone.
pub async fn grade(
    db: &PgPool,
    issue_id: i64,
    analyses: &mut [super::analyses::Analysis],
) -> AppResult<()> {
    if !analyses.iter().any(|a| a.fix_url.is_some()) {
        return Ok(());
    }

    let rows: Vec<(i64, i64, Option<String>)> = sqlx::query_as(
        "select a.id,
                (select count(*) from releases r
                  where r.project_id = i.project_id
                    and r.first_seen > a.created_at)::bigint,
                (select r.version
                   from issue_tags t
                   join releases r
                     on r.project_id = i.project_id and r.version = t.value
                  where t.issue_id = a.issue_id
                    and t.key = 'release'
                    and r.first_seen > a.created_at
                  order by r.first_seen
                  limit 1)
           from issue_analyses a
           join issues i on i.id = a.issue_id
          where a.issue_id = $1 and a.fix_url is not null",
    )
    .bind(issue_id)
    .fetch_all(db)
    .await?;

    for analysis in analyses.iter_mut() {
        if let Some((_, releases_since, regressed_in)) =
            rows.iter().find(|(id, _, _)| *id == analysis.id)
        {
            analysis.fix_verdict = Some(
                verdict(regressed_in.is_some(), *releases_since)
                    .as_str()
                    .to_string(),
            );
            analysis.regressed_in = regressed_in.clone();
        }
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn nothing_shipped_yet_is_not_a_pass() {
        // The failure mode worth avoiding: an agent scoring itself on fixes nobody has deployed.
        assert_eq!(verdict(false, 0), Verdict::Pending);
    }

    #[test]
    fn silence_across_a_release_is_the_pass() {
        assert_eq!(verdict(false, 1), Verdict::Held);
    }

    #[test]
    fn a_recurrence_settles_it_regardless_of_how_much_shipped() {
        assert_eq!(verdict(true, 0), Verdict::Regressed);
        assert_eq!(verdict(true, 9), Verdict::Regressed);
    }

    fn fix(source: &str, verdict: Verdict) -> Fix {
        Fix {
            analysis_id: 1,
            issue_id: 1,
            project_slug: "demo".into(),
            issue_title: "boom".into(),
            source: source.into(),
            fix_url: "https://example.com/pull/1".into(),
            proposed_at: Utc::now(),
            verdict,
            releases_since: 0,
            regressed_in: None,
        }
    }

    #[test]
    fn a_rate_needs_something_settled_to_be_a_rate() {
        let record = tally(&[fix("claude-code", Verdict::Pending)]);
        assert_eq!(record[0].pending, 1);
        assert_eq!(record[0].hold_rate, None);
    }

    #[test]
    fn pending_fixes_do_not_drag_the_rate_down() {
        let record = tally(&[
            fix("claude-code", Verdict::Held),
            fix("claude-code", Verdict::Held),
            fix("claude-code", Verdict::Regressed),
            fix("claude-code", Verdict::Pending),
        ]);
        assert_eq!(record.len(), 1);
        assert_eq!(record[0].hold_rate, Some(2.0 / 3.0));
    }

    #[test]
    fn each_agent_keeps_its_own_record() {
        let record = tally(&[
            fix("ci-triage", Verdict::Regressed),
            fix("claude-code", Verdict::Held),
        ]);
        assert_eq!(record[0].source, "ci-triage");
        assert_eq!(record[0].hold_rate, Some(0.0));
        assert_eq!(record[1].source, "claude-code");
        assert_eq!(record[1].hold_rate, Some(1.0));
    }
}
